# Generated by Django 2.2.7 on 2019-11-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlfield',
            name='status_codes',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
