# Generated by Django 2.2.7 on 2019-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_urlfield_status_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCodeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='urlfield',
            name='status_codes',
        ),
    ]
